{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "self = <TestCases.test_login.Test_testlogin object at 0x000001C32252CBD0>\n\n    def setup(self):\n>       self.driver = webdriver.chrome()\nE       TypeError: 'module' object is not callable\n\nTestCases\\test_login.py:27: TypeError"}, "start": 1685890331518, "stop": 1685890331518, "uuid": "ed393dca-a131-4c9a-bea9-27ebd81874fd", "historyId": "dfc0cd6410304a2a5f92a96423518169", "testCaseId": "dfc0cd6410304a2a5f92a96423518169", "fullName": "TestCases.test_login.Test_testlogin#test_login", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_testlogin"}, {"name": "host", "value": "DESKTOP-2BK3DCT"}, {"name": "thread", "value": "20240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}