{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_sub():\n>       assert 1==2\nE       assert 1 == 2\n\nTestCases\\test_login.py:11: AssertionError"}, "start": 1685458338904, "stop": 1685458338904, "uuid": "780afe22-4673-449c-9b70-b7814a420878", "historyId": "d53d5abbb0cad41d9e33569eaa5cb307", "testCaseId": "963cd0d181bf4115f499e81877501557", "fullName": "TestCases.test_login#test_sub", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-2BK3DCT"}, {"name": "thread", "value": "17744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}